### ISSUE TITLE
Öneri

### ISSUE THREAD

**Issue by mustafakoca99** [izniburak/c-programlama-kod-ornekleri#2]
Dizilerin ve fonksiyonların üzerinde çokça durmanızı öneririm.

**Comment by izniburak** [comment]
Merhaba @mustafakoca99 ,
Aslında bu repoyu okul zamanlarında yaptıklarımı ve karşılaştıklarımı yayınlamak, faydalanmak isteyenlerde inceleyebilsin diye burada paylaştım. Şu an aktif olarak C yazmıyorum. Bu nedenle yeni örnekler ekleyebileceğimi sanmıyorum maalesef. 

Sizlerden gelecek katkılar olursa, repoya ekstra örnekler ekleyebiliriz ama. 

Teşekkürler.

**Comment by mustafakoca99** [comment]
Teşekkür ederim, en kısa zamanda projeleri forklayıp kendi yaptıklarımdan ekleyeceğim.
